### ISSUE TITLE
Follow up

### ISSUE THREAD

**Issue by kisvegabor** [Fabien-Chouteau/lvgl-ada#1]
Hi Fabien,

Based on your [former comment](https://github.com/littlevgl/lvgl/pull/704) I'd like to follow up. 
What is the current state of the Ada binding?

**Comment by Fabien-Chouteau** [comment]
Hi @kisvegabor,

The binding is almost done, I still need to do some polishing and documentation.

Because I did a thin binding, the API is almost the same as the C one. What I want to document is how to integrate ada-lvgl in an Ada project.

And I would like to have an example running on an STM32F4 board, on top of the existing SDL example.

I will keep you updated,

**Comment by kisvegabor** [comment]
Awesome!

If you want we can host this repository in the [littlevgl](https://github.com/littlevgl) organization to keep things in one place. Of course, you would have write access to the repo. It's just an option, leaving it here is perfect too!
